footer:
  - name: Contact
    identifier: mailto
    weight: 1
  - name: Mentions légales
    pageRef: /mentions-legales
    weight: 2
  - name: Politique de confidentialité
    pageRef: /politique-de-confidentialite
    weight: 3
