backend:
  name: git-gateway
  branch: main # Branch to update
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
publish_mode: editorial_workflow
collections:
  - name: "links" # Used in routes, e.g., /admin/collections/blog
    label: "Links" # Used in the UI
    folder: "site/content/links" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Source", name: "source", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
