backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: links
    label: Links
    folder: content/links
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Source', name: 'source', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: 'true' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
